In [6]:
import numpy as np
import math

In [23]:
#16.	NumPy Elementary Mathematical Functions
print("cos",np.cos(math.pi/3))
print("sin",np.sin(math.pi/3))
print("tan",np.tan(math.pi/4))
print("arccos",np.arccos(0))
print("arcsin",np.arcsin(0))
print("arctan",np.arctan(1))
print("cosh",np.cosh(math.pi))
print("sinh",np.sinh(math.pi))
print("tanh",np.tanh(math.pi))
print("arccosh",np.arccosh(math.pi))
print("arcsinh",np.arcsinh(math.pi))
print("sqrt",np.sqrt(9))
l=np.array([3,4,5])
print("exp",np.exp(l))
print("log",np.log(l))
print("log2",np.log2(l))
print("log10",np.log10(l))

cos 0.5000000000000001
sin 0.8660254037844386
tan 0.9999999999999999
arccos 1.5707963267948966
arcsin 0.0
arctan 0.7853981633974483
cosh 11.591953275521519
sinh 11.548739357257746
tanh 0.99627207622075
arccosh 1.8115262724608532
arcsinh 1.8622957433108482
sqrt 3.0
exp [ 20.08553692  54.59815003 148.4131591 ]
log [1.09861229 1.38629436 1.60943791]
log2 [1.5849625  2.         2.32192809]
log10 [0.47712125 0.60205999 0.69897   ]


In [25]:
#17.	NumPy Element Wise Mathematical Operations
a=np.array([2,3,4,5])
a1=np.array([2.2,3.,4.,5.])
b=np.array([9,4,3,2])
print("ADD",np.add(a,b))
print("SUB",np.subtract(a,b))
print("MUL",np.multiply(a,b))
print("DIV",np.divide(a,b))
print("power",np.power(a,b))
print("np.remainder",np.remainder(a,b))
print("reciprocal",np.reciprocal(a1))
print("np.sign(), ",np.sign(a1))
print("np.abs",np.abs(a))
print("np.floor",np.floor(a1))
print("np.ceil",np.ceil(a1))
print("np.round",np.round(a1))

ADD [11  7  7  7]
SUB [-7 -1  1  3]
MUL [18 12 12 10]
DIV [0.22222222 0.75       1.33333333 2.5       ]
power [512  81  64  25]
np.remainder [2 3 1 1]
reciprocal [0.45454545 0.33333333 0.25       0.2       ]
np.sign(),  [1. 1. 1. 1.]
np.abs [2 3 4 5]
np.floor [2. 3. 4. 5.]
np.ceil [3. 3. 4. 5.]
np.round [2. 3. 4. 5.]


In [60]:
#18.	NumPy Aggregate and Statistical Functions
l=np.arange(1,10)
print(l)
print("np.mean()",np.mean(l))
print("np.std()",np.std(l))
print("np.var()",np.var(l))
print("np.sum()",np.sum(l))
print("np.prod()",np.prod(l))
print("np.cumsum()",np.cumsum(l))
print("np.cumprod",np.cumprod(l))
l1=l.reshape((3,3))
print(l1)
print("max",np.max(l1))
print("min",np.min(l1))
print("argmax",np.argmax(l1))
print("argmin",np.argmin(l1))
a=np.arange(10,-4,-1)
a.resize((7,2))
print(a)
print(np.all(a,axis=1))
print(np.any(a,axis=0))


[1 2 3 4 5 6 7 8 9]
np.mean() 5.0
np.std() 2.581988897471611
np.var() 6.666666666666667
np.sum() 45
np.prod() 362880
np.cumsum() [ 1  3  6 10 15 21 28 36 45]
np.cumprod [     1      2      6     24    120    720   5040  40320 362880]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
max 9
min 1
argmax 8
argmin 0
[[10  9]
 [ 8  7]
 [ 6  5]
 [ 4  3]
 [ 2  1]
 [ 0 -1]
 [-2 -3]]
[ True  True  True  True  True False  True]
[ True  True]


In [66]:
#19.	NumPy Example of Where function
a=np.array([4,5,6,7,8,9,10,23,43])
ind=np.where(a<np.mean(a))
print(a[ind])

[ 4  5  6  7  8  9 10]


In [69]:
#20.	NumPy Example of Select function
a=np.arange(12)
condlist=[a<=4,a>4]
clist=[a,a**2]
np.select(condlist,clist)


array([  0,   1,   2,   3,   4,  25,  36,  49,  64,  81, 100, 121])

In [70]:
#21.	NumPy Logical operations for selectively picking values from an array depending on a given condition
l=np.array([4,5,6,7,0,6])
l1=np.array([4,0,7,4,2,0])
print("logical_or",np.logical_or(l,l1))
print("logical_and",np.logical_and(l,l1))


logical_or [ True  True  True  True  True  True]
logical_and [ True False  True  True False False]


In [72]:
#22.	NumPy example of Standard Set Operations
l=np.array([4,5,6,7,0,6])
l1=np.array([4,0,7,4,2,0])
print("union",np.union1d(l,l1))
print("intersection",np.intersect1d(l,l1))
print("set diff",np.setdiff1d(l,l1))


union [0 2 4 5 6 7]
intersection [0 4 7]
set diff [5 6]
