In [71]:
import numpy as np

In [72]:
#1.	Down load the dataset winequality-red.csv file( each column is separated by a semicolon (;)) from the UCI Machine Learning Repository
#2.	Convert it to numPy array, name it as wines (leave the first row of the list) and specify the data type of array as float.
wines=np.genfromtxt('C:/Users/y20cs99/Downloads/winequality-red.csv',skip_header=1,delimiter=';',dtype='float')

In [73]:
wines

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [74]:
#3.	Identify the shape of the array.
wines.shape

(1599, 12)

In [75]:
#4.	Display the element at row 3 and column 4.
wines[2,3]

2.3

In [76]:
#5.	 Display the first three items from the fourth column.
wines[0:3,3]

array([1.9, 2.6, 2.3])

In [77]:
#6.	Display third column from each row.
wines[:,2]

array([0.  , 0.  , 0.04, ..., 0.13, 0.12, 0.47])

In [78]:
#7.	Display fourth row.
wines[3]

array([11.2  ,  0.28 ,  0.56 ,  1.9  ,  0.075, 17.   , 60.   ,  0.998,
        3.16 ,  0.58 ,  9.8  ,  6.   ])

In [79]:
#8.	Assign value 10 to 2nd row and 6th column element.
wines[1,5]=10

In [80]:
wines

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [81]:
#9.	Take the 10th column from wines array and name that slice as slice_new and assign value 666 to all elements of slice_new.
slice_new=wines[:,9]
slice_new[:]=666
slice_new

array([666., 666., 666., ..., 666., 666., 666.])

In [82]:

wines[:,9]

array([666., 666., 666., ..., 666., 666., 666.])

In [83]:
#10.	Display wines array.
wines

array([[7.40e+00, 7.00e-01, 0.00e+00, ..., 6.66e+02, 9.40e+00, 5.00e+00],
       [7.80e+00, 8.80e-01, 0.00e+00, ..., 6.66e+02, 9.80e+00, 5.00e+00],
       [7.80e+00, 7.60e-01, 4.00e-02, ..., 6.66e+02, 9.80e+00, 5.00e+00],
       ...,
       [6.30e+00, 5.10e-01, 1.30e-01, ..., 6.66e+02, 1.10e+01, 6.00e+00],
       [5.90e+00, 6.45e-01, 1.20e-01, ..., 6.66e+02, 1.02e+01, 5.00e+00],
       [6.00e+00, 3.10e-01, 4.70e-01, ..., 6.66e+02, 1.10e+01, 6.00e+00]])

In [84]:
#11.	Find the data type of wines array and Change the data type to int.
wines.dtype

dtype('float64')

In [89]:
#11.	Find the data type of wines array and Change the data type to int.
wines=wines.astype(int)

In [90]:
#12.	Add 10 points to each quality score.
wines[:,11]+10

array([15, 15, 15, ..., 16, 15, 16])

In [91]:
#13.	Find the sum of all the elements in an array
np.sum(wines)

1210398

In [102]:
#14.	Find the sum of all the values in every column
np.sum(wines,axis=1)

array([745, 778, 770, ..., 774, 777, 766])

In [103]:
#15.	Find the sum of all the values in every row.
np.sum(wines,axis=0)

array([  12589,      24,       1,    3350,       0,   25367,   74301,
            81,    4770, 1064934,   31938,    9012])

In [94]:
#16.	Add the quality column to itself.
wines[:,10]=np.add(wines[:,10],wines[:,10])

In [95]:
wines

array([[  7,   0,   0, ..., 666,  18,   5],
       [  7,   0,   0, ..., 666,  18,   5],
       [  7,   0,   0, ..., 666,  18,   5],
       ...,
       [  6,   0,   0, ..., 666,  22,   6],
       [  5,   0,   0, ..., 666,  20,   5],
       [  6,   0,   0, ..., 666,  22,   6]])

In [96]:
#17.	Multiply alcohol by quality.
wines[:,9]*wines[:,10]

array([11988, 11988, 11988, ..., 14652, 13320, 14652])

In [97]:
#18.	Display which wines have a quality rating higher than 5.
wines[wines[:,10]>5,10]

array([18, 18, 18, ..., 22, 20, 22])

In [98]:
#19.	Check if any wines have a quality rating equal to 10.
wines[wines[:,10]==10,10]

array([], dtype=int32)

In [99]:
#20.	Select rows in wines where the quality is over 7
wines[wines[:,10]>7]

array([[  7,   0,   0, ..., 666,  18,   5],
       [  7,   0,   0, ..., 666,  18,   5],
       [  7,   0,   0, ..., 666,  18,   5],
       ...,
       [  6,   0,   0, ..., 666,  22,   6],
       [  5,   0,   0, ..., 666,  20,   5],
       [  6,   0,   0, ..., 666,  22,   6]])

In [100]:
#21.	Display wines with alcohol greater than 10 and quality greater than 7.
wines[(wines[:,9]>10) & (wines[:,10]>7),9:11]

array([[666,  18],
       [666,  18],
       [666,  18],
       ...,
       [666,  22],
       [666,  20],
       [666,  22]])

In [105]:
#22.	Change the shape of wines array.
wines=wines.reshape(12,1599)

In [106]:
wines.shape

(12, 1599)